[package]
name = "hello-world-in-graphul-test"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
graphul = { git = "https://github.com/Phosphorus-M/graphul", branch = "route-exporter" }
shuttle-service = { version = "0.8.0", features = ["web-axum"] }
sync_wrapper = "0.1"